In [1]:
from sklearn import datasets
import numpy as np
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import skfuzzy

In [2]:
iris = datasets.load_iris()
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [7]:
# iris.data.T = tranpor dados do dataset
# c = numero de clusters
# m = qual grupo cada cluster pertence. O valor 2 é o recomentado
# error = criterio de parada. O valor 0.005 é o recomentado
# maxiter = quantas vezes irá fazer a repetição
r = skfuzzy.cmeans(data = iris.data.T, c = 3, m=2, error = 0.005,
                  maxiter = 1000, init = None)
r

(array([[5.88836264, 2.760864  , 4.36311935, 1.39688615],
        [6.77432273, 3.05218168, 5.64592332, 2.05321495],
        [5.00396462, 3.41411703, 1.48276964, 0.25352574]]),
 array([[2.30444733e-03, 1.66607486e-02, 1.37668405e-02, 2.24799567e-02,
         3.76211447e-03, 4.48297049e-02, 1.40114115e-02, 3.11735407e-04,
         4.77462996e-02, 1.19439434e-02, 2.17670908e-02, 5.43593780e-03,
         2.01954550e-02, 5.18196467e-02, 7.26352379e-02, 1.04384596e-01,
         3.55934374e-02, 2.28889321e-03, 6.55895721e-02, 1.41634772e-02,
         2.18705838e-02, 1.03783214e-02, 2.75192280e-02, 1.44745735e-02,
         2.32614544e-02, 1.84734119e-02, 3.58527309e-03, 4.56723714e-03,
         4.32981926e-03, 1.42118290e-02, 1.48105268e-02, 1.77073266e-02,
         4.11615322e-02, 6.35048540e-02, 1.03486309e-02, 1.02056973e-02,
         2.42622932e-02, 6.18394568e-03, 4.11063519e-02, 1.17846445e-03,
         3.58429553e-03, 1.02326978e-01, 3.21934141e-02, 1.43932919e-02,
         3.81528051e-

In [13]:
previsoes_porcentagem = r[1]

#probabilidade de estar no grupo 0 
print(previsoes_porcentagem[0][0])
#probabilidade de estar no grupo 1 
print(previsoes_porcentagem[1][0])
#probabilidade de estar no grupo 2
print(previsoes_porcentagem[2][0])

0.0023044473313626333
0.0010719148269437472
0.9966236378416936


In [17]:
#pegar o grupo com amior porcentagem
# argmax(axis = 0) = maior valor por coluna
previsoes = previsoes_porcentagem.argmax(axis = 0)
previsoes

array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0], dtype=int64)

In [18]:
resultados = confusion_matrix(iris.target, previsoes)
resultados

array([[ 0,  0, 50],
       [47,  3,  0],
       [13, 37,  0]], dtype=int64)